import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import axios from "axios";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Architecture from "../components/Architecture";
import Benifit from "../components/Benifit";
import FAQ from "../components/FAQ";
import Footer from "../components/Footer";
import Reviews from "../components/Reviews";
import Price from "../components/Price";
import Chat from "../components/Chat";
import Upcomming from "../components/Upcomming";
import News from "../components/News";
import { NextSeo } from "next-seo";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextSeo
        title="InvestHere - Your Trusted Investment Partner"
        description="Welcome to InvestHere, your trusted investment partner. We offer a wide range of investment products to help you grow your wealth and achieve your financial goals."
        openGraph={{
          type: "website",
          url: "https://InvestHere.com",
          title: "InvestHere - Your Trusted Investment Partner",
          description:
            "Welcome to InvestHere, your trusted investment partner. We offer a wide range of investment products to help you grow your wealth and achieve your financial goals.",
          images: [
            {
              url: "https://InvestHere.com/InvestHere.jpg",
              width: 1200,
              height: 630,
              alt: "InvestHere",
            },
          ],
        }}
        twitter={{
          handle: "@InvestHere",
          site: "@InvestHere",
          cardType: "summary_large_image",
          title: "InvestHere - Your Trusted Investment Partner",
          description:
            "Welcome to InvestHere, your trusted investment partner. We offer a wide range of investment products to help you grow your wealth and achieve your financial goals.",
          image: "https://InvestHere.com/InvestHere.jpg",
        }}
        jsonLd={{
          "@context": "https://schema.org",
          "@type": "Organization",
          name: "InvestHere",
          legalName: "InvestHere Investments, Inc.",
          url: "https://InvestHere.com",
          logo: "https://InvestHere.com/InvestHere.jpg",
          foundingDate: "2022-01-01",
          sameAs: [
            "https://facebook.com/InvestHere",
            "https://twitter.com/InvestHere",
            "https://linkedin.com/InvestHere",
          ],
          address: {
            "@type": "PostalAddress",
            streetAddress: "123 Main Street",
            addressLocality: "New York",
            addressRegion: "NY",
            postalCode: "10001",
            addressCountry: "USA",
          },
          contactPoint: {
            "@type": "ContactPoint",
            telephone: "+1-212-555-1212",
            contactType: "customer service",
          },
          description:
            "Welcome to InvestHere, your trusted investment partner. We offer a wide range of investment products to help you grow your wealth and achieve your financial goals.",
        }}
      />

      <main className={styles.main}>
        <Navbar id="home" />
        <Header />
        <Architecture />
        <Benifit />
        <Reviews />
        <Price />
        <News />

        <FAQ />
        <Upcomming />
        <Footer />
        <Chat />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
