import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import axios from "axios";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Architecture from "../components/Architecture";
import Benifit from "../components/Benifit";
import FAQ from "../components/FAQ";
import Footer from "../components/Footer";
import Reviews from "../components/Reviews";
import Price from "../components/Price";
import Chat from "../components/Chat";
import Upcomming from "../components/Upcomming";
import News from "../components/News";
import { NextSeo } from "next-seo";
import Projects from "../components/Projects/Projects";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextSeo
        title="KiwiCode - Your Source for Innovative Software Solutions"
        description="At KiwiCode, we craft custom software solutions to meet your unique business needs. Our expert team delivers cutting-edge technology and unparalleled quality."
        openGraph={{
          type: "website",
          url: "https://www.kiwicode.com",
          title: "KiwiCode - Your Source for Innovative Software Solutions",
          description:
            "At KiwiCode, we craft custom software solutions to meet your unique business needs. Our expert team delivers cutting-edge technology and unparalleled quality.",
          images: [
            {
              url: "https://www.kiwicode.com/kiwicode.jpg",
              width: 1200,
              height: 630,
              alt: "KiwiCode",
            },
          ],
        }}
        twitter={{
          handle: "@KiwiCode",
          site: "@KiwiCode",
          cardType: "summary_large_image",
          title: "KiwiCode - Your Source for Innovative Software Solutions",
          description:
            "At KiwiCode, we craft custom software solutions to meet your unique business needs. Our expert team delivers cutting-edge technology and unparalleled quality.",
          image: "https://www.kiwicode.com/kiwicode.jpg",
        }}
        jsonLd={{
          "@context": "https://schema.org",
          "@type": "Organization",
          name: "KiwiCode",
          legalName: "KiwiCode Software Solutions, Inc.",
          url: "https://www.kiwicode.com",
          logo: "https://www.kiwicode.com/kiwicode.jpg",
          foundingDate: "Year Founded",
          sameAs: [
            "https://www.facebook.com/KiwiCode",
            "https://twitter.com/KiwiCode",
            "https://www.linkedin.com/company/kiwicode",
          ],
          address: {
            "@type": "PostalAddress",
            streetAddress: "123 Main Street",
            addressLocality: "City",
            addressRegion: "State",
            postalCode: "ZIP Code",
            addressCountry: "Country",
          },
          contactPoint: {
            "@type": "ContactPoint",
            telephone: "+1-123-456-7890",
            contactType: "customer service",
          },
          description:
            "At KiwiCode, we craft custom software solutions to meet your unique business needs. Our expert team delivers cutting-edge technology and unparalleled quality.",
        }}
      />

      <main className={styles.main}>
        <Navbar id="home" />
        <Header />
        <Architecture />
        {/* <Benifit /> */}
        <Projects />
        <Reviews />
        {/* <Price /> */}
        {/* <Upcomming /> */}

        <News />

        {/* <FAQ /> */}
        <Footer />
        {/* <Chat /> */}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
